# Generated by Django 4.2.2 on 2024-06-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_remove_user_enabled_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_activity', 'Can block user'), ('view_users', 'Can view list of users'), ('view_recipients', 'Can view list of recipients'), ('view_posts', 'Can view list of posts')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
