# Generated by Django 4.2.2 on 2024-06-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_activity', 'Can block user'), ('view_users', 'Can view list of users'), ('view_recipients', 'Can view list of recipients'), ('view_posts', 'Can view list of posts'), ('view_post_logs', 'Can view log of posts')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
