# Generated by Django 4.2.2 on 2024-06-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_send_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус последней отправки'),
        ),
        migrations.AddField(
            model_name='post',
            name='next_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей отправки'),
        ),
        migrations.AddField(
            model_name='postlogs',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('created', 'Создано и готово к рассылке'), ('published', 'В рассылке'), ('canceled', 'Отменено')], default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='postlogs',
            name='result',
            field=models.ForeignKey(blank=True, choices=[('success', 'Успех'), ('failed', 'Ошибка')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.result', verbose_name='Результат попытки'),
        ),
    ]
